services:
  app:
    image: rencedm112/spcf-tes:latest
    volumes:
      - ./.env:/var/www/html/.env
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./docker/database/fs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  database-admin-ui:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - database

  proxy:
    image: nginx:latest
    entrypoint:
      - nginx
    command:
      - -g
      - "daemon off;"
    networks:
      app-network:
        ipv4_address: ${PROXY_IP:-172.16.0.2}
    depends_on:
      - app
      - database
      - database-admin-ui
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "9733:9733"
    volumes:
      - ./docker/proxy/fs/etc/nginx/templates:/etc/nginx/templates
      - ./docker/proxy/fs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  database-data:
  mail-server-data:


networks:
  app-network:
    driver: bridge
    attachable: true
    name: app-network
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.16.0.0/16}
          gateway: ${NETWORK_GATEWAY_IP:-172.16.0.1}
