services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - ENV=development
    volumes:
      - ./:/var/www/html
      - ./docker/app/fs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/app/fs/usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/app/fs/usr/local/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/app/fs/usr/local/etc/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./docker/app/fs/etc/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    networks:
      default:
        aliases:
          - ${DATABASE_HOSTNAME:-database}
    volumes:
      - "./docker/database/fs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  database-admin-app:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file:
      - path: .env
        required: false

  mail-server:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mail-server-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    env_file:
      - path: .env
        required: false

volumes:
  database-data:
  mail-server-data:
