services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.dev
    volumes:
      - ./:/var/www/html
      - ./docker/app/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/app/config/php-fpm/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf
    expose:
      - 9000
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./docker/database/fs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  database-admin-ui:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - database

  mail-server:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mail-server-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  nginx:
    image: nginx:latest
    entrypoint:
      - nginx
    command:
      - -g
      - "daemon off;"
    volumes:
      - ./docker/nginx/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - app

volumes:
  database-data:
  mail-server-data:
